/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Task {
  /**
   * Unique identifier for the task
   */
  id: string;
  /**
   * Unique identifier of the organization to which the task belongs
   */
  organizationId: string;
  /**
   * Title of the task
   */
  title: string;
  /**
   * Description of the task
   */
  description?: string;
  /**
   * Due date and time for the task
   */
  dueDate?: string;
  /**
   * Priority level of the task
   */
  priority?: "low" | "medium" | "high";
  /**
   * Status of the task
   */
  status: "todo" | "in-progress" | "completed";
  /**
   * Tags associated with the task
   */
  tags?: string[];
}
